<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Interfaces\Repositories\ICitas.cs" />
    <Compile Remove="Interfaces\Repositories\IConsultorios.cs" />
    <Compile Remove="Interfaces\Repositories\IGenericRepository1.cs" />
    <Compile Remove="Interfaces\Repositories\ITurno.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\GenericRepository\GenericRepository.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Interfaces\Repositories\" />
  </ItemGroup>

</Project>
